### ISSUE TITLE
One FLMD file per data file or data package? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#1]
**Submitter**: Kim Ely

I suggest the following changes:
It is unclear from the instructions whether a FLDM file is required per data file, or per package.

"Create file-level metadata for each data **file** using the template.
    a. Start new row for each data file"

One FLMD file per package, with a row for each data file makes sense to me. A separate FLMD file per data file would be onerous for data creators, and perhaps not useful for users. 

My suggested correction would be to update the instructions to: "Create file-level metadata for each data package using the template."

**Comment by tvelliquette** [comment]
@regnans Good catch. It should be per data package.
@robcrystalornelas Can you make the change that Kim points out?

**Comment by robcrystalornelas** [comment]
@tvelliquette I can definitely make the changes. Thanks @regnans for catching this, and for making suggestions on how we can update the instructions.

**Comment by robcrystalornelas** [comment]
Thanks to Kim's suggestion, text in the instructions file now indicates we only need one FLMD file per **data package**
