### ISSUE TITLE
FLMD file naming instructions

### ISSUE THREAD

**Issue by tvelliquette** [ess-dive-community/essdive-file-level-metadata#10]
* Documentation reference (URL):
* Submitter: Terri
* Justification (why is this change necessary?): No file naming instructions for flmd file

I suggest the following changes:
For CSV_dd the instructions are to follow the name of the data file. In the case of FLMD, it could include multiple files with different names. So is it just "flmd"?

**Comment by regnans** [comment]
For data packages with a known ID, like the NGEEs, something like NGA123_flmd.csv would be straightforward. From the point of view of preparing files I'd want to have more than flmd.csv to prevent having multiple files with the same name but different content in my system.

**Comment by robcrystalornelas** [comment]
@charuleka suggestions on naming the actual file-level metadata file? 

- Above, Kim provides a solution for data packages with known project IDs, but otherwise we likely want a system of naming beyond just flmd.csv. 
- Maegen has also mentioned this as something that would be useful to specify for the model data archiving guidelines

**Comment by tvelliquette** [comment]
@robcrystalornelas Sounds like confirmation today at July CF meeting is to name the FLMD file "flmd.csv"

**Comment by robcrystalornelas** [comment]
Yes, agreed. I think leave our general recommendation as 'flmd.csv' and if others want to add/modify words in any way they can do that. But 'flmd.csv' can be our recommendation.

**Comment by tvelliquette** [comment]
I added text saying to name file "flmd.csv". If that's all the edits needed related to this issue, then it's done.

**Comment by robcrystalornelas** [comment]
@tvelliquette I just edited a few words in the instructions file, and I think that the asterisk / italics issue is solved now. Closing the issue
