### ISSUE TITLE
Confusion about the _dd.csv instructions

### ISSUE THREAD

**Issue by kristinboye** [ess-dive-community/essdive-file-level-metadata#11]
**Submitter**: Kristin Boye

I suggest the following changes: I am confused with how to implement the recommended data dictionary (_dd.csv) based on the information provided. Looking at the template provided, I think I understand how to compile this file, but then looking at the csv structure and file level metadata instructions I get confused. For example, there are instructions in the "...csv_quick_guide.md" file to provide further specifications for a unit format in the data dictionary, which I think is great, but I just don't understand how it fits with the current formatting of the data dictionary template. 

Sorry, I just need to understand how to construct the data dictionary for "my" reporting format so that it is consistent with the upstream (and hopefully general) ESS-DIVE reporting format requirements.

**Comment by tvelliquette** [comment]
@kristinboye I hope the broader discussion about how all the reporting formats come together will help make this more clear and consistent.

**Comment by robcrystalornelas** [comment]
@vchendrix I want to highlight this issue that we discussed as a group during the March CF partner meeting. Right now, the CF partners are defining the different headers that appear in the CSV files in two different ways.

Terminology file (Kristin and Amy are using this) - When using the terminology file, researchers can provide header names, definitions, units, and more at the **package level**. There is a column in the terminology file where they tell us which files in their data packages use the terms they define in the terminology file. For an example of the terminology file see this section of their README file: https://github.com/ess-dive-community/essdive-hydrologic-monitoring#a-quick-look-at-the-templates

Data Dictionary - The data dictionary defines CSV column headers at the **file level**. For example, if there is a CSV file names soil_data.csv, it would be paired with a data dictionary named soil_data_dd.csv that provides definitions and units for all variables listed in that file's header.  If another CSV file has the exact same variables, we can use an asterisk in data dictionary file name to indicate that the data dictionary applies to more than one file.  An example: https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/CSV_dd/CSV_dd_example.md

**Comment by tvelliquette** [comment]
@robcrystalornelas Are there any changes that I need to make related to this issue?

**Comment by robcrystalornelas** [comment]
It seems like **all** reporting formats will have a data dictionary where column/row names are defined, units provided etc.  Whereas **some** reporting formats will include an additional terminology file where different data flags or other important terms are define.

Ultimately, this will be up to the other reporting formats to provide clarity on how their terminology file differs from the data dictionary.
