### ISSUE TITLE
missing value codes 

### ISSUE THREAD

**Issue by tvelliquette** [ess-dive-community/essdive-file-level-metadata#17]
* Documentation reference (URL):
* Submitter: Terri
* Justification (why is this change necessary?):
Need to add instructions when listing a string of missing value codes
Need to add instructions if data file contains no missing value codes
Need to update the FLMD example since the missing value code field isn't represented correctly (I used a semicolon which we don't list as an option but instead suggest a | or surround list with quotes.

I suggest the following changes:

Possible issues with potential solution
1.	I suppose if the file doesn’t contain any missing values then inserting “N/A” doesn’t actually change anything since that value doesn’t exist in the file.
2.	If there are empty cells with no missing values used to represent those empty cells that brings up a different need. Should that be represented as “blank” or “ ” or “missing values are represented by blank cells”
3. Recommend explain in greater detail about where and how the missing value codes are assigned and what they represent in the Data Dictionary Description field(s). You could add the same or more brief description in the FLMD Notes field.

Need to refer users to the CSV Detailed Guide under Delimiter for how to format fields with multiple entries that contain commas.

**Comment by robcrystalornelas** [comment]
I made a related issue under the CSV reporting format repo, since that is where we have guidance on not using semicolon within cells: https://github.com/ess-dive-community/essdive-csv-structure/issues/6

**Comment by tvelliquette** [comment]
We have since decided that a "semicolon" is okay and that wording needs to be changed in the documentation.

**Comment by tvelliquette** [comment]
I can't seem to get the edit I made to the FLMD quick guide to display. I see it in Markdown.

I added instructional text about using delimiters for multiple missing value code entries rather than forcing users to go back to the CSV delimiter instructions. If you think the text is good and you can get it to commit changes, close it out. 

Here is what I tried to commit:
Report all Missing Value Codes. For columns containing numeric data, use "-9999" as the missing value code \(or modify to match significant figures given the data\). For columns containing character data, use "N/A" as the missing value code. If entering more than one missing value code, use a vertical bar "|" or semicolon ";" instead of a comma or protect the comma with matching double quotation marks around the entire value. For more information about commas not meant to be a delimiter (e.g. used within a cell), refer to the Delimiter section of the CSV Reporting Format Detailed Guide.

**Comment by robcrystalornelas** [comment]
All set now. I copied and pasted over the new text you provided above to the missing value section of the quick guide.
