### ISSUE TITLE
naming data dictionary files and create one dd file or many

### ISSUE THREAD

**Issue by tvelliquette** [ess-dive-community/essdive-file-level-metadata#19]
* Documentation reference (URL):
* Submitter: @tvelliquette 
* Justification (why is this change necessary?): question came up at monthly meeting

Decisions:

- At the June meeting - users could create one data dictionary file and include all fields for all data files. For this file, simply name the file: "dd.csv"
- At the July meeting - users could also continue to create data dictionary files in a one-to-one ratio. For these files, use the current instructions for naming: "filename_dd.csv"

**Comment by robcrystalornelas** [comment]
@tvelliquette I'm closing this issue since we have clarified the naming options for the data dictionary
