### ISSUE TITLE
FLMD template asks for "standards" not "reporting formats"

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#2]
***Term to change**: Which of the FLMD terms would you like to modify? Standard
**Submitter**: Kim Ely
**Justification**: Why is this change necessary? Reporting format, not standard

## I suggest the following changes (leave blank whatever would not change):
* Term name: Reporting format
* Definition of the term:
* Format of the term: 
* Additional Instructions (recommendations regarding content, etc.):
* Examples: 
* Refines (name of the broader term this term refines, if applicable):
* Replaces (name of the existing term that would be replaced by this term, if applicable): Standard

**Comment by robcrystalornelas** [comment]
@tvelliquette I think the intention of naming this field "standard" here was to leave open the possibility that data contributors indicate a reporting format *or* an existing data standard.  Should we rename the field "reporting_format" or something like "standard_or_reporting_format"

**Comment by regnans** [comment]
And I see that the description says reporting format or standard. So perhaps fine to leave the template column name as it is.

**Comment by robcrystalornelas** [comment]
Sounds good, Kim! I'm going to leave this open and get some more feedback on this.

**Comment by regnans** [comment]
No worries. As per my comment above, given the definition in the description I would be happy to leave it as Standard and close this out.

**Comment by robcrystalornelas** [comment]
Sounds good! Closing the issue now.
