### ISSUE TITLE
FLMD quick guide italics text - why?

### ISSUE THREAD

**Issue by tvelliquette** [ess-dive-community/essdive-file-level-metadata#21]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/documents/flmd_quick_guide.md
* Submitter: Terri
* Justification (why is this change necessary?): questioning the use of italics

I suggest the following changes:

I am wondering why in the FLMD quick guide File_name description has italics text and no where else do I find this?

**Comment by robcrystalornelas** [comment]
Thanks for catching that @tvelliquette I missed a backslash to cancel out the italics. All set now: https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/documents/flmd_quick_guide.md#file-name
