### ISSUE TITLE
Asterisk for Wildcard not showing up on ESS-DIVE in File Name

### ISSUE THREAD

**Issue by dylanporyan** [ess-dive-community/essdive-file-level-metadata#27]
**Submitter**: Dylan O'Ryan

Hello,

While reviewing some ESS-DIVE datasets that utilize the File-level Reporting Format, I have found an issue with using asterisks (*) in the file name. As reccomended by the [FLMD instructions]( https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/flmd_instructions.md), users should use an asterisk as a wildcard when the FLMD applies to multiple files.

The issue is that these asterisks do not show up on ESS-DIVE when uploaded (see screenshots to see the removal of the asterisks). It seems that there may need to be an adjustment to the use of the asterisk in file names. The screenshots are from a published dataset on ESS-DIVE ([link](https://data.ess-dive.lbl.gov/view/doi:10.15485/1830417)). _Note_: I have encountered this issue with two datasets so far on ESS-DIVE.

![Screen Shot 2022-05-03 at 9 40 40 AM](https://user-images.githubusercontent.com/85315738/166500200-8b74cfc2-e021-46de-a727-b6a347fd217e.png)

![Screen Shot 2022-05-03 at 9 42 14 AM](https://user-images.githubusercontent.com/85315738/166500232-75708e08-ad9f-4b04-b844-23389f091f90.png)

**Comment by emilyarobles** [comment]
@dylanporyan The asterisks should be used as a wildcard within the FLMD to indicate that a row entry applies to multiple files with similar names, not at the file naming level for FLMD or DD files. Can you point me to the documentation that says that wildcards should be used for file naming?

**Comment by dylanporyan** [comment]
@emilyarobles Thank you for your response and the explanation. 

Within the [CSV Data Dictionary Instructions](https://github.com/ess-dive-community/essdive-file-level-metadata/tree/master/CSV_dd) (Step 5C), the documentation specifically notes to: `Incorporate a wildcard into the filename if data dictionary applies to multiple data files (for example - "soil_cores_*_dd.csv")`.

**Comment by dylanporyan** [comment]
This issue and question arose out of the confusion of how wildcards (*) should be used, which should be used within the FLMD file (and DD file, if applicable) not within an actual file name. Documentation has been revised to addressed this confusion. Done.
