### ISSUE TITLE
Noting Header_Row Amount on FLMD File

### ISSUE THREAD

**Issue by dylanporyan** [ess-dive-community/essdive-file-level-metadata#28]
**Submitter**: Dylan O'Ryan

**Question for @tvelliquette:** It is unclear on how to note header_row amount within data files on the FLMD file. Based on the CSV reporting format reccomendation for units on data files, we have included a units row "immediately below the Column Name as a next row." While we (ESS-DIVE) were attempting to parse some data files using the CSV and FLMD reporting format, I was unable to find guidance on noting header_row amounts on both FLMD and CSV reporting formats.

Should users of the CSV and FLMD reporting formats add an additional column to the FLMD file to note the header_row amount in a data file? Or is there an alternative suggestion for noting header_row amounts?

**Comment by tvelliquette** [comment]
@dylanporyan I am not sure I understand the question. What is meant by "header_row amounts"?

**Comment by dylanporyan** [comment]
Hi @tvelliquette, for header_row amount -- we are meaning the number of rows before the start of the data. For example, 

This particular data file has 2 header_rows (column_header row and unit row).
<img width="187" alt="Screen Shot 2022-09-13 at 8 55 29 AM" src="https://user-images.githubusercontent.com/85315738/189949470-f5a78d8e-d165-4b88-a8a7-3389d717ce26.png">

Whereas, this particular data file has 5 header_rows (using the Hydrological Monitoring RF and has the header_row number as a field).
<img width="704" alt="Screen Shot 2022-09-13 at 8 54 44 AM" src="https://user-images.githubusercontent.com/85315738/189949782-7eb229eb-6446-4970-a37d-3cd3d4e1fcb4.png">

Please let me know if this makes sense or if I can clarify further.

**Comment by tvelliquette** [comment]
@dylanporyan That makes sense. This version 1.0 of the FLMD reporting format is a streamlined version of the initials drafts. Header information was part of the CSV Reporting Format very early on. The decision was made to start small but to continue to refine and potentially expand the reporting format in newer versions. There are quite a few issues/discussions that might provide a reason for at least a minor update.

**Comment by dylanporyan** [comment]
Version 1.1.0 (v1.1.0) has been released and merged within the main branch. This subsequent version has added the "header_rows" as a column header within the FLMD file, as requested. Done.
