### ISSUE TITLE
why are csv_dd and flmd templates in xlsx format?

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#3]
**Submitter**:

I suggest the following changes: it seems that csv would be fine here, and would prevent users from uploading xlsx

**Comment by robcrystalornelas** [comment]
Good point, @tvelliquette, are you OK with me switching the .xlsx data dictionary files over to CSVs?

**Comment by tvelliquette** [comment]
@robcrystalornelas @regnans Switching to CSV is fine. This will be the case for any other .xlsx files that users will need to complete. I don't know if this will result in any changes to the documentation/instructions.

**Comment by robcrystalornelas** [comment]
@tvelliquette I've got the data dictionary uploaded as a CSV. Are you OK with me deleting the excel file from the repository? If we're OK with removing that excel file, my next to-do will be:

- [ ] go through documentation and make sure nothing is linking to the deleted excel file.

**Comment by robcrystalornelas** [comment]
@tvelliquette I went through and made sure all links to the template within the repo now point to the CSV version of the data dictionary instead of Excel. Going to close this issue.

**Comment by regnans** [comment]
ah, I forgot about the download issue. That's not one of GitHub's best features! Thanks for your response, that makes sense to have excel for download. I'll close this again.

**Comment by robcrystalornelas** [comment]
:+1:  Sounds good, Kim!
