### ISSUE TITLE
Question: retain unused columns in FLMD? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#34]
If I am creating an FLMD file with just the required and recommended columns, should I use the template and fill unused columns with N/As, or create a modified FLMD containing only columns with data? 
thanks,
Kim

**Comment by emilyarobles** [comment]
Hi Kim, 

Please revise the template to only include the fields relevant to your data. Thank you for this question, I'll add a reminder to clarify this in our instructions.

Emily

**Comment by regnans** [comment]
Thanks for the clarification. I will follow this recommendation for further data submissions. 
Kim
