### ISSUE TITLE
v1.1 Review (2024-06-17)

### ISSUE THREAD

**Issue by dylanporyan** [ess-dive-community/essdive-file-level-metadata#36]
@emilyarobles I have reviewed the v1.1 branch of the File Level Metadata reporting format GitHub and have the following recommendations.

## File Level Metadata 

**General Comment:**
- [x] Elevate the standardized reporting format keywords and controlled file naming convention lists within GitHub. I am finding it difficult to find these easily within the FLMD GitHub.

**FLMD: [ReadMe.md](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/README.md)**
- [x] Link in ["Updated in v1.1.0" section](https://github.com/ess-dive-community/essdive-file-level-metadata/tree/release-v2.0?tab=readme-ov-file#updates-in-v200) for `FLMD standard name` does not link correctly
- [x] In the second bullet under `Removing excess optional fields`, it says "The optional field _missing value code_...", however the field is "missing_value_code**s**" (missing "s") 

**FLMD: [SUMMARY.md](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/SUMMARY.md)**
- [x] `Download FLMD template` bullet links out to v1 template, should be updated to link to v1.1
- [x] `Download CSV Data Dictionary template` bullet links out to v1 template, should be updated to link to v1.1

**FLMD: [FLMD Instructions](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/flmd_instructions.md)**
- [x] Instruction step **1b**, the following **i** step should be entered below (i.e., fix spacing / markdown issue).
- [x] Instruction step 3, template links to v1 and should be updated to link to v1.1
- [x] Instruction step 7 is the only step that contains a period at the end, may want to remove to make consistent with other steps
- [x] `Contents of the Elements` contain complete list of headers, including removed headers from v1 (e.g., coordinates, lat/long). Recommend removing these, if these are removed in v1.1.

**FLMD: [FLMD Quick Guide](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/flmd_quick_guide.md)**
- [x] Standard field definition should link out to `Standard FLMD Term List` 
- [x] For `header_rows`, consider making the `Required, Recommended or Optional` field "Optional, required if dataset has multiple header rows" to elevate the conditional requirement.
- [x] For `column_or_row_name_position`, consider making the `Required, Recommended or Optional` field "Optional, required if rows or columns are provided before the row/column names" to elevate the conditional requirement.

**FLMD: [FLMD Template](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/flmd_template.csv)**
- [x] This template includes the v1 headers that were removed in v1.1, these should likely be removed from the template

**FLMD: [FLMD Template Example](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/flmd_template_example.md)**
- [x] This example template includes the v1 headers that were removed in v1.1, these should likely be removed from the template
- [x] Recommend including the two added fields within the example template: `header_rows` and `column_or_row_name_position`

----
## Data Dictionary

**DD: [ReadMe.md](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/CSV_dd/README.md)**
- [x] Step 1 of instructions, template links to v1 template, should be updated to link to v1.1
- [x] Contents of the CSV_dd, add `missing_value_codes` to this list as it has been merged to DD in v1.1

**DD: [DD Quick Guide](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/CSV_dd/csv_dd_quick_guide.md)**
- [x] `missing_value_codes` is missing from this list and should be included due to move from FLMD to DD in v1.1

**DD: [DD Template Example](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/CSV_dd/csv_dd_example.md)**

**DD: [DD Template](https://github.com/ess-dive-community/essdive-file-level-metadata/blob/release-v2.0/CSV_dd/CSV_dd_template.csv)**
- [x] `missing_value_codes` field is missing and should be added to template

**Comment by tvelliquette** [comment]
Thanks so much @emilyarobles . I'm trying to update and use the V2.0 and had to create my own template. I did not do a complete review but just trying to navigate to the new, updated information and was confused by the items you pointed out. 

I don't think you have this one in your list - on the FLMD quick guide, the list of elements has one fewer than found below. "file_version" is in the table but not in the list. Which one is correct?

**Comment by emilyarobles** [comment]
@tvelliquette Hi Terri, thank you for sharing your input! I've just updated the FLMD quick guide to address Dylan's review as well as the missing file_version in the list. 

We're working through the additional revisions today to release this version by this Friday (9/6). If you have any feedback in the meantime please let me know.

**Comment by dylanporyan** [comment]
v1.1.0 of the File Level Metadata reporting format has been merged and released. All issues described above have been addressed before release. Done.
