### ISSUE TITLE
Suggested addition: number of character guidance for "column name" and "long name"

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#5]
**Submitter**:

I suggest the following changes:
Guidance on limits on number of characters that can be used in a Column_Name (and long name) would be useful. 
https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/CSV_dd/CSV_dd_quick_guide.md

**Comment by tvelliquette** [comment]
@regnans I don't know that putting a character limit on long name is needed. It shouldn't be long since the description will describe what the field contains. 
@robcrystalornelas - column name limit might be where ESS-DIVE developers have an opinion. Maybe a recommendation of 50 characters or less. I've see some recommendations online for 30 or less and 128 max.

**Comment by robcrystalornelas** [comment]
@tvelliquette I can follow-up with development team to see if something along the lines of <50 characters or <128 characters would be helpful for ingesting/reading the files

**Comment by regnans** [comment]
@tvelliquette agree. Guidance on character limit for long name is not required.

**Comment by tvelliquette** [comment]
I had someone point out the field names can get quite long if using CF Standard Names.

**Comment by regnans** [comment]
that's an interesting approach! 
A maximum number of characters for the variable name could be a suggestion, not a requirement. I still think it's useful guidance for people coming up with new variable names (and let's the really old school people know they can have more that 8 characters).

**Comment by tvelliquette** [comment]
This actually goes back to CSV field name instructions. There aren't any guidelines on the number characters. 

I believe we decided not to worry about this. Correct? So done?

**Comment by regnans** [comment]
ok.
