### ISSUE TITLE
Clarification: should all of the "_dd.csv" files be listed in the FLMD table? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#7]
**Submitter**:

I suggest the following changes: Clarify which files should be listed in the table in the instructions. https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/flmd_instructions.md

I don't feel strongly either way as to whether the _dd.csv files should be listed. But perhaps it should be clarified if other metadata files are listed, for example protocol documents and other supporting information.

**Comment by tvelliquette** [comment]
@regnans @robcrystalornelas great question about the _dd files. This gets at what files to include from all the reporting formats. When thinking about FLMD we did think about other types of data files including zip files (which can have all types of files inside) and tried to make it broadly fit thus so many optional fields. I wonder if some of the other reporting formats actually have flmd per the specific data type. This is the idea that popped up again and again that not only reporting format per data type but FLMD per data type but here we started broadly like with the CSV.

**Comment by regnans** [comment]
My question could be clarified as: Should the FLMD table list all files in the package, or only data files? 
I think the FLMD as it is currently defined is flexible enough to accommodate different types of data files other than csv. As a user, it would work to list all data files in a single FLMD file.

**Comment by tvelliquette** [comment]
@regnans I just sent an email to Rob saying that we should discuss this at the CF meeting next week. It does seem logical to list ALL files and not just data files. It would also give an opportunity to give a brief description of these new, extra files coming out of the reporting format with possibly some kind of boiler plate language to describe them.

**Comment by robcrystalornelas** [comment]
As Terri mentioned, I've added this to the agenda for our February CF meeting. I'm curious to hear what other groups developing reporting formats envision.

**Comment by robcrystalornelas** [comment]
Notes from Feb 2021 CEP Meeting:

- What do we do with zip files? We want descriptions of what is in zip files, not just the zip file itself
- How to provide FLMD for data packages with hundreds of similar files (e.g., spectra files)
   - use wild card
   - If we are OK with batch files/using wildcard and other forms of text-analysis/regular expression then we need to be clear around rules and formatting for wildcards.

**Comment by tvelliquette** [comment]
Adding the dd.csv files to the flmd table makes a nice checklist of the data package.

**Comment by robcrystalornelas** [comment]
@tvelliquette Great additions to the instructions about zip files. Also, I updated text in instructions to get at Kim's first point above, which is, should data dictionaries be listed in FLMD.  Added this line to instructions under step 6:

"Also list any data dictionaries you create as part of your file-level metadata (described in step 1a). "
