### ISSUE TITLE
standard or reporting format in csv_dd guide? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#8]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-file-level-metadata/blob/master/CSV_dd/CSV_dd_quick_guide.md
* Submitter: Kim
* Justification (why is this change necessary?): possibly inconsistent use of terminology

I suggest the following changes: In the dd quick guide short tables should the metadata elements "standard statement" and "standard definition" use the word standard or reporting format?

**Comment by tvelliquette** [comment]
@regnans Good catch. It shows up the same way in the CSV_quick_guide so it will need to be changed. @robcrystalornelas FLMD has - reporting format statement; reporting format definition

No matter how much you proof . . . .

**Comment by robcrystalornelas** [comment]
I updated both guides so that they now say 'reporting format statement' and 'reporting format definition'

Thanks for pointing this out @regnans!
