### ISSUE TITLE
Instruction clarification: Should the dd include a separate row for each column in all cases? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-file-level-metadata#9]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-file-level-metadata/tree/master/csv_dd_instructions
* Submitter: Kim
* Justification (why is this change necessary?): Additional detail needed in instructions. 

In the case of data that has many columns with the same dd metadata (unit, definition, data type), is a row required for every column? Or can the similar columns be represented by a single row, similar to how multiple similar files can be represented in the FLMD? 
 For example, in spectra data there are 2150 columns, labeled wave_350, wave_351 .... wave_2500. Should this be represented in the dd as 2150 unique rows, or a single row with the variable name of "wave_*"?

**Comment by tvelliquette** [comment]
@regnans Excellent point. I don't see why they can't also be represented by the wildcard. @robcrystalornelas?

**Comment by tvelliquette** [comment]
Need to add text to the instructions for this so I'm tagging myself to review and edit instructions with Rob's help if necessary. - @tvelliquette @robcrystalornelas

**Comment by robcrystalornelas** [comment]
Since @tvelliquette has updated instructions to allow for multiple data dictionary entries to apply to multiple column/row names, I'll close this issue.
